apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .Values.dataVolume.name }}
  labels:  
    special: {{ include "vm-workloads.name" . }}
    helm.sh/chart: {{ include "vm-workloads.chart" . }}
    vm.kubevirt.io/instance: {{ .Release.Name }}
    vm.kubevirt.io/managed-by: {{ .Release.Service }}
spec:
  source:
    registry:
            url: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
  pvc:
    accessModes:
      - {{ .Values.dataVolume.accessMode }}
    resources:
      requests:
        storage: {{ .Values.dataVolume.size }}
