apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
labels:  
  app.kubernetes.io/instance: vm-workloads  
spec:
  ports:
  - name: seed-ssh-svc
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/managed-by: Helm    
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  type: {{ .Values.service.type }}
