apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:  
    special: {{ include "vm-workloads.name" . }}
    helm.sh/chart: {{ include "vm-workloads.chart" . }}
    vm.kubevirt.io/instance: {{ .Release.Name }}
    vm.kubevirt.io/managed-by: {{ .Release.Service }}  
spec:
  ports:
  - name: seed-ssh-svc
    nodePort: {{ .Values.service.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app.kubernetes.io/managed-by: Helm    
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  type: {{ .Values.service.type }}
