apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: {{ .Values.vmName.name }}
  labels:  
    app.kubernetes.io/instance: vm-workloads
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: seedpvcdisk
    machine:
      type: "q35"
    resources:
      requests:
        memory: {{ .Values.resources.requests.memory }}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: seedpvcdisk
    persistentVolumeClaim:
      claimName:  {{ .Values.claimName.name }}
status: {}
