# Default values for single-vm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

claimName:
  name: seed-datavolume

dataVolume:
  name: seed-datavolume
  accessMode: ReadWriteOnce
  size: 110Gi  
image:
  repository: docker://172.16.5.154:5000
  name: seed
  tag: v1.0
  
vmName:
  name: seed-vm1

service:
  name: vmi-seed-ssh-svc 
  type: NodePort
  targetPort: 22
  nodePort: 30000
  port: 27017
  externalTrafficPolicy: Cluster

resources:
  requests:
    memory: 16Gi
