# Default values for single-vm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

claimName:
  name: seed-dv-1.0

dataVolume:
  name: seed-dv-1.0
  accessMode: ReadWriteOnce
  size: 110Gi  
image:
  repository: docker://172.16.5.150:5000
  name: seed
  tag: v1.0
  
vmName:
  name: seed-vm-1.0

service:
  name: seed-vm-svc 
  type: NodePort
  targetPort: 22
  nodePort: 31000
  port: 27018
  externalTrafficPolicy: Cluster

resources:
  requests:
    memory: 16Gi
